//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 LordPE.rc 使用
//
#define IDD_DIALOG_MAIN                 101
#define IDI_ICON_ICON                   103
#define IDD_DIALOG_ABOUT                105
#define IDD_DIALOG_PE_VIEWER            107
#define IDD_DIALOG_SECTION_TABLE        109
#define IDD_DIALOG_DIRECTORY_TABLE      111
#define IDD_DIALOG_EXPORT_TABLE         113
#define IDD_DIALOG_EXPORT_TABLE2        114
#define IDD_DIALOG_EXPORT_TABLE1        116
#define IDD_DIALOG_IMPORT_TABLE         116
#define IDD_DIALOG_RESOURCE_TABLE       117
#define IDD_DIALOG_RELOCATION_TABLE     118
#define IDD_DIALOG_BOUND_IMPORT_TABLE   119
#define IDD_DIALOG_IAT_TABLE            120
#define IDC_BUTTON_PE_VIEWER            1002
#define IDC_BUTTON_ABOUT                1003
#define IDC_BUTTON_LOGOUT               1004
#define IDC_BUTTON_EXIT                 1004
#define IDC_LIST_PROCESS                1011
#define IDC_LIST_MODULE                 1012
#define IDC_EDIT_ENTRY_POINT            1025
#define IDC_EDIT_SIZE_OF_IMAGE          1026
#define IDC_EDIT_DATA_DIRECTORY_RVA2    1026
#define IDC_EDIT_BASE_OF_CODE           1027
#define IDC_EDIT_DATA_DIRECTORY_RVA3    1027
#define IDC_EDIT_IMAGE_BASE             1028
#define IDC_EDIT_DATA_DIRECTORY_RVA0    1028
#define IDC_EDIT_BASE_OF_DATA           1029
#define IDC_EDIT_SECTION_ALIGNMENT      1030
#define IDC_EDIT_DATA_DIRECTORY_RVA5    1030
#define IDC_EDIT_FILE_ALIGNMENT         1031
#define IDC_EDIT_DATA_DIRECTORY_RVA6    1031
#define IDC_EDIT_MAGIC                  1032
#define IDC_EDIT_DATA_DIRECTORY_RVA7    1032
#define IDC_EDIT_SUB_SYSTEM             1033
#define IDC_EDIT_DATA_DIRECTORY_RVA4    1033
#define IDC_EDIT_TIME_DATE_STAMP        1034
#define IDC_EDIT_DATA_DIRECTORY_RVA9    1034
#define IDC_EDIT_SIZE_OF_HEADERS        1035
#define IDC_EDIT_DATA_DIRECTORY_RVA10   1035
#define IDC_EDIT_NUMBER_OF_SECTIONS     1036
#define IDC_EDIT_DATA_DIRECTORY_RVA11   1036
#define IDC_EDIT_CHARACTERISTICS        1037
#define IDC_EDIT_DATA_DIRECTORY_RVA8    1037
#define IDC_EDIT_CHECK_SUM              1038
#define IDC_EDIT_DATA_DIRECTORY_RVA13   1038
#define IDC_EDIT_SIZE_OF_OPTIONAL_HEADER 1039
#define IDC_EDIT_DATA_DIRECTORY_RVA14   1039
#define IDC_EDIT_NUM_OF_RVA_AND_SIZES   1040
#define IDC_EDIT_DATA_DIRECTORY_RVA15   1040
#define IDC_BUTTON_PE_VIEWER_CLOSE      1041
#define IDC_EDIT_DATA_DIRECTORY_RVA12   1041
#define IDC_LIST_SECTION_TABLE          1042
#define IDC_BUTTON_DIRECTORY_TABLE_CLOSE 1042
#define IDC_BUTTON_DIRECTORY_TABLE      1043
#define IDC_EDIT_DATA_DIRECTORY_SIZE1   1043
#define IDC_EDIT_DATA_DIRECTORY_SIZE2   1044
#define IDC_BUTTON_SECTION_TABLE        1045
#define IDC_EDIT_DATA_DIRECTORY_SIZE3   1045
#define IDC_EDIT_DATA_DIRECTORY_SIZE0   1046
#define IDC_EDIT_DATA_DIRECTORY_SIZE5   1047
#define IDC_EDIT_DATA_DIRECTORY_SIZE6   1048
#define IDC_EDIT_DATA_DIRECTORY_SIZE7   1049
#define IDC_EDIT_DATA_DIRECTORY_SIZE4   1050
#define IDC_EDIT_DATA_DIRECTORY_SIZE9   1051
#define IDC_EDIT_DATA_DIRECTORY_SIZE10  1052
#define IDC_EDIT_DATA_DIRECTORY_SIZE11  1053
#define IDC_EDIT_DATA_DIRECTORY_SIZE8   1054
#define IDC_EDIT_DATA_DIRECTORY_SIZE13  1055
#define IDC_EDIT_DATA_DIRECTORY_SIZE14  1056
#define IDC_EDIT_DATA_DIRECTORY_SIZE15  1057
#define IDC_EDIT_DATA_DIRECTORY_SIZE12  1058
#define IDC_EDIT_DATA_DIRECTORY_RVA1    1059
#define IDC_BUTTON_EXPORT_TABLE         1060
#define IDC_EDIT1                       1062
#define IDC_EDIT_EXPORT_TABLE           1062
#define IDC_EDIT_IMPORT_TABLE           1063
#define IDC_BUTTON_IMPORT_TABLE         1064
#define IDC_EDIT_RESOURCE_TABLE         1064
#define IDC_BUTTON_RESOURCE             1065
#define IDC_EDIT_RELOCATION_TABLE       1065
#define IDC_BUTTON_RELOCATION           1066
#define IDC_EDIT_BOUND_IMPORT_TABLE     1066
#define IDC_BUTTON_BOUND_IMPORT         1067
#define IDC_EDIT_IAT_TABLE              1067
#define IDC_BUTTON_IAT                  1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
